### ISSUE TITLE
Breaks Ubuntu due to a Requests module upgrade

### ISSUE THREAD

**Issue by nikolay** [httpie/httpie-unixsocket#2]
```
Downloading/unpacking git+https://github.com/msabramo/httpie-unixsocket.git
  Cloning https://github.com/msabramo/httpie-unixsocket.git to /tmp/pip-J2zDhW-build
  Running setup.py (path:/tmp/pip-J2zDhW-build/setup.py) egg_info for package from git+https://github.com/msabramo/httpie-unixsocket.git

Downloading/unpacking httpie>=0.7.0 from https://pypi.python.org/packages/2.7/h/httpie/httpie-0.9.0-py2.py3-none-any.whl#md5=76c94093b32e5257c097b15519f2b64a (from httpie-unixsocket==1.0.2)
Downloading/unpacking requests-unixsocket (from httpie-unixsocket==1.0.2)
  Downloading requests-unixsocket-0.1.4.tar.gz
  Running setup.py (path:/tmp/pip_build_root/requests-unixsocket/setup.py) egg_info for package requests-unixsocket

    Installed /tmp/pip_build_root/requests-unixsocket/pbr-0.10.7-py2.7.egg
    [pbr] Processing SOURCES.txt
    warning: LocalManifestMaker: standard file '-c' not found

    warning: no previously-included files found matching '.gitignore'
    warning: no previously-included files found matching '.gitreview'
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
Downloading/unpacking requests>=2.3.0 from https://pypi.python.org/packages/py2.py3/r/requests/requests-2.5.1-py2.py3-none-any.whl#md5=11dc91bc96c5c5e0b566ce8f9c9644ab (from httpie>=0.7.0->httpie-unixsocket==1.0.2)
Downloading/unpacking Pygments>=1.5 from https://pypi.python.org/packages/2.7/P/Pygments/Pygments-2.0.2-py2-none-any.whl#md5=98f29db02f4b22f58a2d3f60646e1e1f (from httpie>=0.7.0->httpie-unixsocket==1.0.2)
Installing collected packages: httpie, requests-unixsocket, httpie-unixsocket, requests, Pygments
  Found existing installation: httpie 0.8.0
    Uninstalling httpie:
      Successfully uninstalled httpie
  Running setup.py install for requests-unixsocket
    [pbr] Reusing existing SOURCES.txt
  Running setup.py install for httpie-unixsocket

  Found existing installation: requests 2.3.0
    Uninstalling requests:
      Successfully uninstalled requests
  Found existing installation: Pygments 1.6
    Uninstalling Pygments:
      Successfully uninstalled Pygments
Successfully installed httpie requests-unixsocket httpie-unixsocket requests Pygments
Cleaning up...
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2476, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2190, in load
    ['__name__'])
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 61, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python2.7/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 25, in <module>
    from requests.compat import IncompleteRead
ImportError: cannot import name IncompleteRead

```

**Comment by msabramo** [comment]
It looks like you (perhaps inadvertently?) did a `sudo pip install` not in a virtualenv (i.e.: to the system Python)?

If so, that would be the problem here. It is best to always `pip install` to a virtualenv. Installing new python packages to the system python is fraught with peril. 

If that's the case, you'll have to remove the stuff that got added and reinstall the appropriate apt-get packages to get stuff back to how it was.

**Comment by nikolay** [comment]
I know it's best to always use virtualenv or pyenv and I do this in my dev environment, but it's not always worth the complications especially when httpie is available as a Ubuntu package and Requests is built-in. It would make the installation much easier if those dependencies' version numbers can be justified.

**Comment by msabramo** [comment]
Here's the requirements from `setup.py`:

``` python
    install_requires=[
        'httpie>=0.7.0',
        'requests_unixsocket'
    ],
```

And requests_unixsocket requires `requests>=1.1`

I don't see what I can do to make it better unfortunately.
